In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
import re

In [ ]:
#Load Dataset
df=pd.read_csv("/content/morgan_stanely.csv")

In [ ]:
#Check the data first rows and columns.
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,78,CUST1223,ACC33287,Credit,Withdrawal,Savings Account,Firm E,South,Manager 4,06-01-2023,81300.425190,40843.56193,0.330474,484,13
1,21,CUST8266,ACC58667,Savings,Withdrawal,Credit Card,Firm A,South,Manager 2,17-02-2023,9269.640373,61183.03953,0.089688,836,18
2,176,CUST9420,ACC99117,Credit,Transfer,Home Loan,Firm A,East,Manager 1,13-09-2023,28138.552650,85460.13405,0.340010,451,25
3,167,CUST5253,ACC10117,Loan,Payment,Mutual Fund,Firm D,Central,Manager 1,28-05-2024,83943.556980,100525.35900,0.605383,487,13
4,46,CUST1223,ACC74631,Savings,Deposit,Credit Card,Firm A,East,Manager 4,12-05-2023,77104.456470,57425.69930,1.042441,393,10

In [ ]:
# checking the columns,count and datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TransactionID      800 non-null    int64
 1   CustomerID         800 non-null    object
 2   AccountID          800 non-null    object
 3   AccountType        800 non-null    object
 4   TransactionType    800 non-null    object
 5   Product            800 non-null    object
 6   Firm               800 non-null    object
 7   Region             800 non-null    object
 8   Manager            800 non-null    object
 9   TransactionDate    800 non-null    object
 10  TransactionAmount  800 non-null    float64
 11  AccountBalance     800 non-null    float64
 12  RiskScore          800 non-null    float64
 13  CreditRating       800 non-null    int64
 14  TenureMonths       800 non-null    int64
dtypes: float64(3), int64(3), object(9)
memory usage: 93.9+ KB

In [ ]:
# checking count,mean,std,min,etc....
df.describe()

,TransactionID,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,99.786250,55194.889273,72764.355699,0.473380,568.526250,119.870000
std,57.460793,28940.337792,35623.574024,0.239982,155.620111,67.356806
min,1.000000,-36173.695550,-62548.722060,-0.300118,306.000000,6.000000
25%,50.000000,34842.164247,48684.199043,0.312271,437.000000,63.000000
50%,99.500000,53768.493325,72908.053070,0.485829,565.000000,118.000000
75%,150.000000,74729.551358,95574.572673,0.632799,699.500000,178.000000
max,199.000000,154662.045800,180539.287700,1.254704,848.000000,238.000000

**Task 1: Data Cleaning and Formatting (10 Marks)**

**1.1** Remove/treat any special characters or non-numeric entries from financial fields.

In [ ]:
#We need to remove everything except digits and decimal points.
financial_cols = ["TransactionAmount", "AccountBalance", "RiskScore", "CreditRating", "TenureMonths"]

for col in financial_cols:
    df[col] = df[col].astype(str)

    for i in range(len(df)):
        df.at[i, col] = re.sub(r'[^0-9.]', '', df.at[i, col])

    df[col] = pd.to_numeric(df[col], errors='coerce')

 **1.2** Convert currency amounts into numerical format.

In [ ]:
#Check the data types
print(df["TransactionAmount"].dtype)
print(df["AccountBalance"].dtype)

float64
float64

In [ ]:
#Display sample values
df["TransactionAmount"].head(5)

0    81300.425190
1     9269.640373
2    28138.552650
3    83943.556980
4    77104.456470
Name: TransactionAmount, dtype: float64

In [ ]:
#Check for missing values
df.isnull().sum()

TransactionID        0
CustomerID           0
AccountID            0
AccountType          0
TransactionType      0
Product              0
Firm                 0
Region               0
Manager              0
TransactionDate      0
TransactionAmount    0
AccountBalance       0
RiskScore            0
CreditRating         0
TenureMonths         0
dtype: int64

**1.3** Validate and Format Date Columns

In [ ]:
import pandas as pd

df = pd.read_csv("/content/morgan_stanely.csv")

In [ ]:
# Validate the date column
# Your dates are in DD-MM-YYYY format, so use:
df["TransactionDate"] = pd.to_datetime(
    df["TransactionDate"],
    format="%d-%m-%Y"
)

In [ ]:
#Check if any invalid dates exist
print(df["TransactionDate"].isnull().sum())

0

In [ ]:
#Format the dates
df["TransactionDate"] = df["TransactionDate"].dt.strftime("%Y-%m-%d")

In [ ]:
#Verify the result
df["TransactionDate"].head()

0    2023-01-06
1    2023-02-17
2    2023-09-13
3    2024-05-28
4    2023-05-12
Name: TransactionDate, dtype: object

**1.4** Ensure account types and transaction categories are standardized.

In [ ]:
print("Unique Account Types:")
print(df["AccountType"].unique())

print("\nUnique Transaction Types:")
print(df["TransactionType"].unique())

Unique Account Types:
['Credit' 'Savings' 'Loan' 'Current']

Unique Transaction Types:
['Withdrawal' 'Transfer' 'Payment' 'Deposit']

In [ ]:
#Save the cleaned dataset
df.to_csv("cleaned_morgan_stanley.csv", index=False)