**Task 3**:

Customer Profile Building
Group accounts by activity levels:

High, Medium, Low based on transaction frequency on
your analysis and rubrics. Do not forget to mention the rubric in the headings.

In [1]:
#import libraries
import pandas as pd

In [2]:
df=pd.read_csv("/content/processed_morgan_stanley.csv")

In [3]:
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,...,AccountBalance,RiskScore,CreditRating,TenureMonths,Year,Month,NetAmount,PreviousTransaction,GapDays,Status
0,72,CUST1498,ACC10117,Current,Deposit,Mutual Fund,Firm D,North,Manager 1,2023-01-30,...,46657.21790,0.227450,659,16,2023,January,52336.34278,NaN,NaN,Active
1,173,CUST2067,ACC10117,Current,Transfer,Personal Loan,Firm D,East,Manager 1,2023-04-30,...,180539.28770,0.396153,393,45,2023,April,-77018.97098,2023-01-30,90.0,Dormant
2,127,CUST9528,ACC10117,Savings,Transfer,Mutual Fund,Firm C,East,Manager 4,2023-06-20,...,80204.67302,0.457247,618,181,2023,June,-65805.20213,2023-04-30,51.0,Active
3,180,CUST2541,ACC10117,Current,Withdrawal,Credit Card,Firm A,Central,Manager 4,2023-07-14,...,70489.10944,0.185195,494,223,2023,July,-89395.76266,2023-06-20,24.0,Active
4,114,CUST8091,ACC10117,Savings,Withdrawal,Credit Card,Firm A,South,Manager 3,2023-08-04,...,99972.73002,-0.010665,619,225,2023,August,18353.15647,2023-07-14,21.0,Active

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        800 non-null    int64
 1   CustomerID           800 non-null    object
 2   AccountID            800 non-null    object
 3   AccountType          800 non-null    object
 4   TransactionType      800 non-null    object
 5   Product              800 non-null    object
 6   Firm                 800 non-null    object
 7   Region               800 non-null    object
 8   Manager              800 non-null    object
 9   TransactionDate      800 non-null    object
 10  TransactionAmount    800 non-null    float64
 11  AccountBalance       800 non-null    float64
 12  RiskScore            800 non-null    float64
 13  CreditRating         800 non-null    int64
 14  TenureMonths         800 non-null    int64
 15  Year                 800 non-null    int64
 16  Month                800 non-null    object
 17  NetAmount            800 non-null    float64
 18  PreviousTransaction  611 non-null    object
 19  GapDays              611 non-null    float64
 20  Status               800 non-null    object
dtypes: float64(5), int64(4), object(12)
memory usage: 131.4+ KB

In [5]:
df["AccountID"].unique()

array(['ACC10117', 'ACC10996', 'ACC11062', 'ACC11188', 'ACC11285',
       'ACC11837', 'ACC12182', 'ACC12334', 'ACC13357', 'ACC15228',
       'ACC15359', 'ACC15671', 'ACC15925', 'ACC16241', 'ACC16664',
       'ACC17688', 'ACC18057', 'ACC18140', 'ACC18177', 'ACC19156',
       'ACC19178', 'ACC20297', 'ACC21264', 'ACC21429', 'ACC21719',
       'ACC21878', 'ACC22036', 'ACC22255', 'ACC22799', 'ACC23736',
       'ACC23985', 'ACC24070', 'ACC24508', 'ACC24880', 'ACC24981',
       'ACC25132', 'ACC25811', 'ACC26026', 'ACC26940', 'ACC26956',
       'ACC26973', 'ACC28154', 'ACC28292', 'ACC28295', 'ACC28305',
       'ACC28612', 'ACC29007', 'ACC29231', 'ACC29356', 'ACC29396',
       'ACC29477', 'ACC29646', 'ACC30146', 'ACC30787', 'ACC30852',
       'ACC31539', 'ACC31902', 'ACC32212', 'ACC32627', 'ACC32890',
       'ACC33287', 'ACC34119', 'ACC34431', 'ACC34568', 'ACC34821',
       'ACC35163', 'ACC35419', 'ACC36079', 'ACC37688', 'ACC38559',
       'ACC39161', 'ACC39482', 'ACC39500', 'ACC39529', 'ACC39544',
       'ACC40939', 'ACC40952', 'ACC41829', 'ACC42467', 'ACC42710',
       'ACC42903', 'ACC43309', 'ACC43771', 'ACC45101', 'ACC45521',
       'ACC45907', 'ACC45968', 'ACC46953', 'ACC47099', 'ACC48303',
       'ACC48501', 'ACC49140', 'ACC49180', 'ACC49364', 'ACC49395',
       'ACC49422', 'ACC49774', 'ACC50439', 'ACC50817', 'ACC51009',
       'ACC51200', 'ACC51593', 'ACC51971', 'ACC52131', 'ACC52650',
       'ACC53466', 'ACC53865', 'ACC54589', 'ACC55331', 'ACC55729',
       'ACC57516', 'ACC57597', 'ACC57700', 'ACC57872', 'ACC58078',
       'ACC58667', 'ACC60432', 'ACC61827', 'ACC61926', 'ACC62446',
       'ACC62809', 'ACC64022', 'ACC64393', 'ACC64785', 'ACC65144',
       'ACC65545', 'ACC66086', 'ACC66190', 'ACC67701', 'ACC67713',
       'ACC69323', 'ACC70314', 'ACC70460', 'ACC70741', 'ACC71388',
       'ACC71426', 'ACC71938', 'ACC72197', 'ACC73104', 'ACC74631',
       'ACC74656', 'ACC75675', 'ACC76549', 'ACC76597', 'ACC76699',
       'ACC77533', 'ACC77592', 'ACC77638', 'ACC77773', 'ACC78089',
       'ACC78178', 'ACC78581', 'ACC78589', 'ACC80131', 'ACC80442',
       'ACC81631', 'ACC82298', 'ACC82381', 'ACC82926', 'ACC82947',
       'ACC83005', 'ACC83269', 'ACC83581', 'ACC83848', 'ACC86784',
       'ACC87006', 'ACC87602', 'ACC88252', 'ACC88286', 'ACC88449',
       'ACC88516', 'ACC89098', 'ACC90887', 'ACC91220', 'ACC91723',
       'ACC92104', 'ACC92360', 'ACC92558', 'ACC94203', 'ACC94242',
       'ACC94907', 'ACC95164', 'ACC95774', 'ACC96277', 'ACC96868',
       'ACC97411', 'ACC99117', 'ACC99409', 'ACC99549'], dtype=object)

In [6]:
account_activity = df.groupby("AccountID").size().reset_index(name="Transactioncount")
print(account_activity.head())

  AccountID  Transactioncount
0  ACC10117                 9
1  ACC10996                 8
2  ACC11062                 4
3  ACC11188                 2
4  ACC11285                 5

In [7]:
account_activity["Transactioncount"].describe()

count    189.000000
mean       4.232804
std        2.322137
min        1.000000
25%        2.000000
50%        4.000000
75%        6.000000
max       13.000000
Name: Transactioncount, dtype: float64

**3.1** Group accounts by activity levels: High, Medium, Low based on transaction frequency on
your analysis and rubrics. Do not forget to mention the rubric in the headings.

In [8]:
def activity_level(count):
    if count >= 6:
        return "High"
    elif count >= 3:
        return "Medium"
    else:
        return "Low"

account_activity["ActivityLevel"] = account_activity["Transactioncount"].apply(activity_level)

In [9]:
account_activity["ActivityLevel"].value_counts()

ActivityLevel
Medium    92
Low       49
High      48
Name: count, dtype: int64

In [10]:
print(account_activity.head())

  AccountID  Transactioncount ActivityLevel
0  ACC10117                 9          High
1  ACC10996                 8          High
2  ACC11062                 4        Medium
3  ACC11188                 2           Low
4  ACC11285                 5        Medium

**3.2** Segment customers by average balance and transaction volume.

In [11]:
#Calculate Average Balance
df["AverageBalance"] = df.groupby("AccountID")["AccountBalance"].transform("mean")

In [12]:
#Calculate Transaction Volume
transaction_volume = df.groupby("AccountID").size().reset_index(name="TransactionVolume")

In [13]:
df["AverageBalance"].describe()

count       800.000000
mean      72764.355699
std       15552.620055
min        7017.436865
25%       64075.264140
50%       72852.561447
75%       81819.292810
max      117133.776550
Name: AverageBalance, dtype: float64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        800 non-null    int64
 1   CustomerID           800 non-null    object
 2   AccountID            800 non-null    object
 3   AccountType          800 non-null    object
 4   TransactionType      800 non-null    object
 5   Product              800 non-null    object
 6   Firm                 800 non-null    object
 7   Region               800 non-null    object
 8   Manager              800 non-null    object
 9   TransactionDate      800 non-null    object
 10  TransactionAmount    800 non-null    float64
 11  AccountBalance       800 non-null    float64
 12  RiskScore            800 non-null    float64
 13  CreditRating         800 non-null    int64
 14  TenureMonths         800 non-null    int64
 15  Year                 800 non-null    int64
 16  Month                800 non-null    object
 17  NetAmount            800 non-null    float64
 18  PreviousTransaction  611 non-null    object
 19  GapDays              611 non-null    float64
 20  Status               800 non-null    object
 21  AverageBalance       800 non-null    float64
dtypes: float64(6), int64(4), object(12)
memory usage: 137.6+ KB

In [15]:
#merge the transaction volume into df:
df = df.merge(transaction_volume, on="AccountID", how="left")

In [16]:
#Create the customer segment
def customer_segment(row):

    if row["AverageBalance"] >= 81819 and row["TransactionVolume"] >= 6:
        return "Premium"

    elif row["AverageBalance"] >= 64075 and row["TransactionVolume"] >= 3:
        return "Regular"

    else:
        return "Basic"

In [17]:
df["CustomerSegment"] = df.apply(customer_segment, axis=1)

In [18]:
df[["AccountID","AverageBalance","TransactionVolume","CustomerSegment"]].head()

  AccountID  AverageBalance  TransactionVolume CustomerSegment
0  ACC10117    94082.590727                  9         Premium
1  ACC10117    94082.590727                  9         Premium
2  ACC10117    94082.590727                  9         Premium
3  ACC10117    94082.590727                  9         Premium
4  ACC10117    94082.590727                  9         Premium

In [19]:
#Count customers in each segment
customer_segments = df.groupby("CustomerSegment")["AccountID"].nunique()

print(customer_segments)

CustomerSegment
Basic      86
Premium    10
Regular    93
Name: AccountID, dtype: int64

**3.3**  Create profiles for:
○ High-net inflow accounts
○ High-frequency low-balance accounts
○ Accounts with negative or near-zero balances

In [20]:
net_inflow = df.groupby("AccountID")["NetAmount"].sum().reset_index()

net_inflow.rename(columns={"NetAmount":"NetInflow"}, inplace=True)

In [21]:
high_net = net_inflow.sort_values(by="NetInflow",ascending=False)
high_net.head()

    AccountID      NetInflow
69   ACC38559  195846.243974
112  ACC57700  171403.143000
55   ACC31539  128947.199760
102  ACC51971  115097.311765
18   ACC18177  102494.720970

In [22]:
high_frequency_low_balance = df[
    (df["TransactionVolume"] >= 6) &
    (df["AverageBalance"] < 64075)
]

In [23]:
high_frequency_low_balance = high_frequency_low_balance.drop_duplicates("AccountID")

In [24]:
# High-net inflow accounts
high_frequency_low_balance[
    ["AccountID", "AverageBalance", "TransactionVolume"]
]

    AccountID  AverageBalance  TransactionVolume
50   ACC15671    54565.019303                  6
81   ACC18177    58248.054195                  6
141  ACC24508    57275.485464                  7
189  ACC29231    54530.479503                  7
429  ACC50817    59021.066076                  7
454  ACC53466    52903.763152                  6
625  ACC77592    60269.221350                  7

In [25]:
#Accounts with negative
negative_balance = df[df["AccountBalance"] < 0]

negative_balance = negative_balance.drop_duplicates(subset="AccountID")

print(negative_balance[["AccountID", "AccountBalance"]])

    AccountID  AccountBalance
30   ACC11837     -467.139424
71   ACC17688    -6998.284258
86   ACC18177    -6158.757250
92   ACC19156   -31233.114930
162  ACC26940   -22668.046670
230  ACC32212   -28676.452550
257  ACC34431    -6111.634329
308  ACC39529    -8628.929364
396  ACC48501    -6629.775977
427  ACC49774    -2135.472998
433  ACC50817    -6314.634095
454  ACC53466    -1896.114086
489  ACC58667    -5589.440835
496  ACC60432    -2466.768368
569  ACC70741    -7984.433781
601  ACC73104    -3147.142659
611  ACC75675    -2141.591777
639  ACC77773    -2427.573420
655  ACC78589   -13199.362900
728  ACC89098    -5909.198808
785  ACC97411   -62548.722060

In [26]:
# near-zero balances

near_zero_balance = df[
    (df["AccountBalance"] >= 0) &
    (df["AccountBalance"] <= 1000)
]

near_zero_balance = near_zero_balance.drop_duplicates(subset="AccountID")

print(near_zero_balance[["AccountID", "AccountBalance"]])

    AccountID  AccountBalance
400  ACC48501      771.449057
791  ACC99549      261.171238

In [27]:
df.to_csv("3rd dataset.morgan.csv", index=False)